export const URL_SD = 'https://dases-proto.herokuapp.com/sd'
export const URL_USER = 'https://dases-proto.herokuapp.com/users'
export const URL_NONCE = 'https://dases-proto.herokuapp.com/nonce'
export const URL_VERIFY = 'https://dases-proto.herokuapp.com/verify'
// export const URL_PERSONNAL_INFORMATION = 'https://dases-proto.herokuapp.com/personnal_information'

// export const URL_SD = 'http://localhost:5000/sd'
// export const URL_USER = 'http://localhost:5000/users'
// export const URL_NONCE = 'http://localhost:5000/nonce'
// export const URL_VERIFY = 'http://localhost:5000/verify'
// export const URL_PERSONNAL_INFORMATION = 'http://localhost:5000/personal_information'
